import { CategoryRule } from "@/types";

export const DEFAULT_CATEGORY_RULES: CategoryRule[] = [
  // NEEDS
  { keyword: "rent", category: "Needs" },
  { keyword: "apartment", category: "Needs" },
  { keyword: "electricity", category: "Needs" },
  { keyword: "electric", category: "Needs" },
  { keyword: "water bill", category: "Needs" },
  { keyword: "water", category: "Needs" },
  { keyword: "gas bill", category: "Needs" },
  { keyword: "petrol", category: "Needs" },
  { keyword: "fuel", category: "Needs" },
  { keyword: "epic internet", category: "Needs" },
  { keyword: "epic mobile", category: "Needs" },
  { keyword: "epic", category: "Needs" },
  { keyword: "internet", category: "Needs" },
  { keyword: "mobile phone", category: "Needs" },
  { keyword: "road tax", category: "Needs" },
  { keyword: "car loan", category: "Needs" },
  { keyword: "car insurance", category: "Needs" },
  { keyword: "health insurance", category: "Needs" },
  { keyword: "wedding savings", category: "Needs" },
  { keyword: "weddings", category: "Needs" },
  // WANTS
  { keyword: "alphamega", category: "Wants" },
  { keyword: "alpha mega", category: "Wants" },
  { keyword: "wolt", category: "Wants" },
  { keyword: "foody", category: "Wants" },
  { keyword: "mcdonalds", category: "Wants" },
  { keyword: "burger king", category: "Wants" },
  { keyword: "papajohns", category: "Wants" },
  { keyword: "papa johns", category: "Wants" },
  { keyword: "fridays", category: "Wants" },
  { keyword: "zorbas", category: "Wants" },
  { keyword: "taverna", category: "Wants" },
  { keyword: "sea food boil", category: "Wants" },
  { keyword: "loukou donuts", category: "Wants" },
  { keyword: "brunch", category: "Wants" },
  { keyword: "stephania", category: "Wants" },
  { keyword: "stehania", category: "Wants" },
  { keyword: "gym", category: "Wants" },
  { keyword: "new body fitness", category: "Wants" },
  { keyword: "myfitness", category: "Wants" },
  { keyword: "gymshark", category: "Wants" },
  { keyword: "myprotein", category: "Wants" },
  { keyword: "netflix", category: "Wants" },
  { keyword: "apple music", category: "Wants" },
  { keyword: "icloud", category: "Wants" },
  { keyword: "spotify", category: "Wants" },
  { keyword: "hbo", category: "Wants" },
  { keyword: "crunchyroll", category: "Wants" },
  { keyword: "openai", category: "Wants" },
  { keyword: "bumble", category: "Wants" },
  { keyword: "metal plan", category: "Wants" },
  { keyword: "revolut", category: "Wants" },
  { keyword: "ikea", category: "Wants" },
  { keyword: "celio", category: "Wants" },
  { keyword: "athienitis", category: "Wants" },
  { keyword: "kyprianos", category: "Wants" },
  { keyword: "skroutz", category: "Wants" },
  { keyword: "sklavenitis", category: "Wants" },
  { keyword: "barber", category: "Wants" },
  { keyword: "pharmacy", category: "Wants" },
  { keyword: "psixologos", category: "Wants" },
  { keyword: "periptero", category: "Wants" },
  { keyword: "bolt", category: "Wants" },
  { keyword: "clothing", category: "Wants" },
  { keyword: "night out", category: "Wants" },
  { keyword: "entertainment", category: "Wants" },
  { keyword: "padel", category: "Wants" },
  { keyword: "bowling", category: "Wants" },
  { keyword: "escape room", category: "Wants" },
  { keyword: "go karts", category: "Wants" },
  { keyword: "steam", category: "Wants" },
  { keyword: "riot", category: "Wants" },
  { keyword: "playstation", category: "Wants" },
  { keyword: "nintendo", category: "Wants" },
  { keyword: "borderlands", category: "Wants" },
  { keyword: "nvidia", category: "Wants" },
  { keyword: "geforce", category: "Wants" },
  { keyword: "apple", category: "Wants" },
  { keyword: "tattoo", category: "Wants" },
  { keyword: "san remo", category: "Wants" },
  { keyword: "mont parnausse", category: "Wants" },
  { keyword: "superhome", category: "Wants" },
  // SAVINGS
  { keyword: "cnp insurance", category: "Savings" },
  { keyword: "cnp", category: "Savings" },
  { keyword: "savings account", category: "Savings" },
  { keyword: "savings", category: "Savings" },
  { keyword: "emergency fund", category: "Savings" },
  { keyword: "investing", category: "Savings" },
  { keyword: "stocks", category: "Savings" },
  { keyword: "gold", category: "Savings" },
];
