import { CategoryRule } from "@/types";

export const DEFAULT_CATEGORY_RULES: CategoryRule[] = [
  // INTERNAL SAVINGS TRANSFERS — checked first so they win over other rules
  { keyword: "to eur savings", category: "Savings" },
  { keyword: "savings for weddings", category: "Savings" },
  // NEEDS — housing, utilities, transport essentials, insurance
  { keyword: "irene andrea michael", category: "Needs" },
  { keyword: "rent", category: "Needs" },
  { keyword: "apartment", category: "Needs" },
  { keyword: "electricity authority", category: "Needs" },
  { keyword: "electricity", category: "Needs" },
  { keyword: "electric", category: "Needs" },
  { keyword: "water bill", category: "Needs" },
  { keyword: "water", category: "Needs" },
  { keyword: "gas bill", category: "Needs" },
  { keyword: "petrol", category: "Needs" },
  { keyword: "fuel", category: "Needs" },
  { keyword: "fill n' go", category: "Needs" },
  { keyword: "fill n go", category: "Needs" },
  { keyword: "m.g. petrol", category: "Needs" },
  { keyword: "epic internet", category: "Needs" },
  { keyword: "epic mobile", category: "Needs" },
  { keyword: "epic", category: "Needs" },
  { keyword: "internet", category: "Needs" },
  { keyword: "mobile phone", category: "Needs" },
  { keyword: "road transport department", category: "Needs" },
  { keyword: "road tax", category: "Needs" },
  { keyword: "car loan", category: "Needs" },
  { keyword: "car insurance", category: "Needs" },
  { keyword: "health insurance", category: "Needs" },
  { keyword: "gov.cy", category: "Needs" },
  // WANTS — food, entertainment, subscriptions, shopping, personal care
  { keyword: "alphamega", category: "Wants" },
  { keyword: "alpha mega", category: "Wants" },
  { keyword: "lidl", category: "Wants" },
  { keyword: "wolt", category: "Wants" },
  { keyword: "foody", category: "Wants" },
  { keyword: "mcdonald", category: "Wants" },
  { keyword: "burger king", category: "Wants" },
  { keyword: "papa john", category: "Wants" },
  { keyword: "pizza hut", category: "Wants" },
  { keyword: "kfc", category: "Wants" },
  { keyword: "tgi fridays", category: "Wants" },
  { keyword: "fridays", category: "Wants" },
  { keyword: "zorbas", category: "Wants" },
  { keyword: "taverna", category: "Wants" },
  { keyword: "tavernaki", category: "Wants" },
  { keyword: "t' aneipota", category: "Wants" },
  { keyword: "ricky's burgers", category: "Wants" },
  { keyword: "ricky burgers", category: "Wants" },
  { keyword: "sea food boil", category: "Wants" },
  { keyword: "loukou bakery", category: "Wants" },
  { keyword: "loukou donuts", category: "Wants" },
  { keyword: "loukou", category: "Wants" },
  { keyword: "bean bar", category: "Wants" },
  { keyword: "costa coffee", category: "Wants" },
  { keyword: "brunch", category: "Wants" },
  { keyword: "stephania", category: "Wants" },
  { keyword: "stehania", category: "Wants" },
  { keyword: "gym", category: "Wants" },
  { keyword: "new body gym", category: "Wants" },
  { keyword: "myfitness", category: "Wants" },
  { keyword: "gymshark", category: "Wants" },
  { keyword: "myprotein", category: "Wants" },
  { keyword: "whoop", category: "Wants" },
  { keyword: "netflix", category: "Wants" },
  { keyword: "apple music", category: "Wants" },
  { keyword: "icloud", category: "Wants" },
  { keyword: "spotify", category: "Wants" },
  { keyword: "hbo", category: "Wants" },
  { keyword: "crunchyroll", category: "Wants" },
  { keyword: "openai", category: "Wants" },
  { keyword: "claude.ai", category: "Wants" },
  { keyword: "tinder", category: "Wants" },
  { keyword: "bumble", category: "Wants" },
  { keyword: "metal plan", category: "Wants" },
  { keyword: "revolut", category: "Wants" },
  { keyword: "ikea", category: "Wants" },
  { keyword: "celio", category: "Wants" },
  { keyword: "posh boutique", category: "Wants" },
  { keyword: "sneaker10", category: "Wants" },
  { keyword: "amazon", category: "Wants" },
  { keyword: "athienitis", category: "Wants" },
  { keyword: "kyprianos", category: "Wants" },
  { keyword: "skroutz", category: "Wants" },
  { keyword: "sklavenitis", category: "Wants" },
  { keyword: "polyvios polycarpou", category: "Wants" },
  { keyword: "polyvios", category: "Wants" },
  { keyword: "eoa nicosia", category: "Wants" },
  { keyword: "nicolas erotokritou", category: "Wants" },
  { keyword: "barber", category: "Wants" },
  { keyword: "pharmacy", category: "Wants" },
  { keyword: "psixologos", category: "Wants" },
  { keyword: "three star kiosk", category: "Wants" },
  { keyword: "periptero", category: "Wants" },
  { keyword: "bolt", category: "Wants" },
  { keyword: "chauffeurio", category: "Wants" },
  { keyword: "parkaround", category: "Wants" },
  { keyword: "clothing", category: "Wants" },
  { keyword: "night out", category: "Wants" },
  { keyword: "entertainment", category: "Wants" },
  { keyword: "padel", category: "Wants" },
  { keyword: "bowling", category: "Wants" },
  { keyword: "escape room", category: "Wants" },
  { keyword: "go karts", category: "Wants" },
  { keyword: "steam", category: "Wants" },
  { keyword: "riot games", category: "Wants" },
  { keyword: "riot", category: "Wants" },
  { keyword: "g2a", category: "Wants" },
  { keyword: "playstation", category: "Wants" },
  { keyword: "nintendo", category: "Wants" },
  { keyword: "borderlands", category: "Wants" },
  { keyword: "nvidia", category: "Wants" },
  { keyword: "geforce", category: "Wants" },
  { keyword: "apple", category: "Wants" },
  { keyword: "tattoo", category: "Wants" },
  { keyword: "san remo", category: "Wants" },
  { keyword: "mont parnausse", category: "Wants" },
  { keyword: "superhome", category: "Wants" },
  // SAVINGS — insurance policies, transfers to savings accounts
  { keyword: "cnp insurance", category: "Savings" },
  { keyword: "cnp", category: "Savings" },
  { keyword: "savings account", category: "Savings" },
  { keyword: "savings", category: "Savings" },
  { keyword: "emergency fund", category: "Savings" },
  { keyword: "investing", category: "Savings" },
  { keyword: "stocks", category: "Savings" },
  { keyword: "gold", category: "Savings" },
];
