import { CategoryRule } from "@/types";

export const DEFAULT_CATEGORY_RULES: CategoryRule[] = [
  // NEEDS — housing, utilities, transport, insurance
  { keyword: "rent", category: "Needs" },
  { keyword: "mortgage", category: "Needs" },
  { keyword: "electricity", category: "Needs" },
  { keyword: "water bill", category: "Needs" },
  { keyword: "gas bill", category: "Needs" },
  { keyword: "internet", category: "Needs" },
  { keyword: "mobile phone", category: "Needs" },
  { keyword: "phone bill", category: "Needs" },
  { keyword: "petrol", category: "Needs" },
  { keyword: "fuel", category: "Needs" },
  { keyword: "road tax", category: "Needs" },
  { keyword: "car loan", category: "Needs" },
  { keyword: "car insurance", category: "Needs" },
  { keyword: "health insurance", category: "Needs" },
  { keyword: "life insurance", category: "Needs" },
  // WANTS — groceries, food, entertainment, subscriptions, shopping
  { keyword: "lidl", category: "Wants" },
  { keyword: "aldi", category: "Wants" },
  { keyword: "tesco", category: "Wants" },
  { keyword: "sainsbury", category: "Wants" },
  { keyword: "supermarket", category: "Wants" },
  { keyword: "grocery", category: "Wants" },
  { keyword: "wolt", category: "Wants" },
  { keyword: "uber eats", category: "Wants" },
  { keyword: "deliveroo", category: "Wants" },
  { keyword: "just eat", category: "Wants" },
  { keyword: "mcdonald", category: "Wants" },
  { keyword: "burger king", category: "Wants" },
  { keyword: "papa john", category: "Wants" },
  { keyword: "pizza hut", category: "Wants" },
  { keyword: "kfc", category: "Wants" },
  { keyword: "starbucks", category: "Wants" },
  { keyword: "costa coffee", category: "Wants" },
  { keyword: "gym", category: "Wants" },
  { keyword: "gymshark", category: "Wants" },
  { keyword: "myprotein", category: "Wants" },
  { keyword: "netflix", category: "Wants" },
  { keyword: "spotify", category: "Wants" },
  { keyword: "apple music", category: "Wants" },
  { keyword: "icloud", category: "Wants" },
  { keyword: "hbo", category: "Wants" },
  { keyword: "disney", category: "Wants" },
  { keyword: "crunchyroll", category: "Wants" },
  { keyword: "youtube premium", category: "Wants" },
  { keyword: "openai", category: "Wants" },
  { keyword: "amazon", category: "Wants" },
  { keyword: "ikea", category: "Wants" },
  { keyword: "zara", category: "Wants" },
  { keyword: "h&m", category: "Wants" },
  { keyword: "barber", category: "Wants" },
  { keyword: "pharmacy", category: "Wants" },
  { keyword: "bolt", category: "Wants" },
  { keyword: "uber", category: "Wants" },
  { keyword: "steam", category: "Wants" },
  { keyword: "playstation", category: "Wants" },
  { keyword: "nintendo", category: "Wants" },
  { keyword: "xbox", category: "Wants" },
  { keyword: "revolut", category: "Wants" },
  // SAVINGS — transfers to savings, investments
  { keyword: "savings account", category: "Savings" },
  { keyword: "savings", category: "Savings" },
  { keyword: "emergency fund", category: "Savings" },
  { keyword: "investing", category: "Savings" },
  { keyword: "investment", category: "Savings" },
  { keyword: "stocks", category: "Savings" },
  { keyword: "etf", category: "Savings" },
  { keyword: "pension", category: "Savings" },
];
